### ISSUE TITLE
maybe you should add some sort of safeguard for the "overwrite save" option

### ISSUE THREAD

**Issue by Dman0o9** [Ninja-Cookie/BRCTools#2]
as the title says. i accidentally tapped the backspace key and it permanently wiped my entire save file.

**Comment by Ninja-Cookie** [comment]
Being this is primarily a speedrun practice tool, I didn't want to add anything that would slow down switching between practice saves, however a user could safegaurd this already by unbinding the key in BRCTools/Keybinds.cfg config file or through a mod managers config editing page, so they are forced to click it by activating the menu instead.
